id: P009430
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG9562
  title: ཁ་རག་གཉོས་ཀྱི་གདུང་རབས་ཁྱད་པར་འཕགས་པ་དང་རླངས་ཀྱི་གདུང་བརྒྱུད་སོགས།
  author: ''
  volumes:
    22d2ca0d7a9b459ca173368a3fa684f9:
      image_group_id: I1KG9582
      title: ''
      volume_number: 1
      total_pages: 402
      base_file: v001.txt
