id: I3BEB0CA9
legacy_id: P009430
ocr_import_info:
  bdrc_scan_id: W1KG9562
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T01:34:39'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:34:03.340097+00:00'
last_modified: 2022-09-01 02:34:12.239095
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9562
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9562
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཁ་རག་གཉོས་ཀྱི་གདུང་རབས་ཁྱད་པར་འཕགས་པ་དང་རླངས་ཀྱི་གདུང་བརྒྱུད་སོགས།
  author: ཕག་མོ་གྲུ་པ་སྡེ་སྲིད ༠༡་བྱང་ཆུབ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.8104121329599115
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I1KG9582:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9582
      total_pages: 402
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9582.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.8104121329599115
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
