id: I3BEB0CA9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T01:37:16+00:00'
last_modified: '2022-06-08T10:58:55.732588+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9562
  title: ཁ་རག་གཉོས་ཀྱི་གདུང་རབས་ཁྱད་པར་འཕགས་པ་དང་རླངས་ཀྱི་གདུང་བརྒྱུད་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C09A:
      image_group_id: I1KG9582
      title: ''
      total_pages: 402
      order: 1
      base_file: C09A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
